version: "3"

services:
  mysql:
    image: mysql:5.7
    environment:
      MYSQL_USER: mehdi
      MYSQL_PASSWORD: mehdi
      MYSQL_DATABASE: mydb
      MYSQL_HOST: localhost
      MYSQL_ROOT_PASSWORD: root
    ports:
      - 3308:3306
    restart: unless-stopped
    volumes:
      - .docker/db:/var/lib/mysql
 
  phpmyadmin:
    depends_on:
      - mysql
    image: phpmyadmin/phpmyadmin
    environment:
      PMA_HOST: mysql
    links:
      - mysql:mysql
    ports:
      - 8181:80
    restart: always